### ISSUE TITLE
Choosing multiple books to watch from the same search result

### ISSUE THREAD

**Issue by annadorottya** [markszabo/fszek_figyelo#1]
Currently I can only choose one book from a search result and it redirects to the main page automatically. If I want to e.g. watch all books from an author then I have to go back to the previous page.
So I believe it would be a good feature to be able to choose multiple books and maybe add a "Done" button to the top of the table.

**Comment by markszabo** [comment]
Implemented in 98ba45c1aed17b6d17573032435b0fe61c860cb7, deployed to prod. Closing this issue now.
